version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack

artifacts:
  files:
    - index.html
    - babel.html
    - reactdemo.html
    - favicon.png
    - styles/main.css
    - images/*
    - dist/bundle.js
